# Error Handling

- 옵저버블에서 에러 이벤트를 방출하면 구독이 종료되면 구독자는 더이상 새로운 이벤트를 받지 못함
- ex) 옵저버블이 네트워크 요청을 처리하고, 구독자가 UI를 업데이트하는 패턴이 있다
    - 보통 UI를 업데이트하는 코드는 넥스트 이벤트에서 실행되는데, 에러이벤트가 전달되면 구독이 종료되고 더이상 넥스트 이벤트가 전달되지 않음
    - 그래서 UI를 업데이트하는 코드는 실행되지 않음

## RxSwift는 두가지로 이러한 문제를 해결

### 첫번째로, **에러 이벤트가 전달되면 새로운 옵저버블을 리턴 (catch 연산자를 이용)**

- **catch 연산자는 넥스트 이벤트와 컴플리티드 이벤트는 구독자에게 그대로 전달**
- **반면 옵저버블에서 에러 이벤트를 방출하면 새로운 옵저버블 혹은 기본값으로 바꿔서 구독자에게 전달**
- 네트워크 요청 코드에서 많이 사용 → 요청이 실패 했을 때 로컬 캐시를 사용하거나, 기본값을 사용하도록 구현
- 네트워크 요청을 생각 → 서버에 접속할 수 없거나, url이 잘못 되었다면 에러 이벤트를 전달
- 에러 이벤트가 그대로 전달되면 ui가 더이상 업데이트 되지 않아서 엡 사용할 수 없음
- **catch 연산자를 이용해서 옵저버블로 바꿔서 전달하고 옵저버블에서 기본 값이나 로컬 캐시를 방출하도록 하면 이런 문제가 해결**

### 두번째로, **에러가 발생하면 옵저버블을 다시 구독 (retry 연산자를 사용)**

- 에러가 발생하지 않을 때 까지 무한정 재시도 하거나, 재시도 횟수를 제한하는 방법을 제공
- **retry는 소스 옵저버블에서 에러가 발생하면, 옵저버블에 대한 구독을 해지하고 새로운 구독을 시작**
- 새로운 구독이 시작되기 때문에 모든 작업은 처음부터 다시 진행
- 옵저버블에서 오류가 발생하지 않으면 정상 종료되고, 에러가 발생하면 또 다시 새로운 구독을 시작

Catch 연산자 예시

catchAndReturn 예시

retry 예시

retryWhen 예시